// User Roles
const USER_ROLES = {
  USER: 'user',
  VENDOR: 'vendor',
  ADMIN: 'admin'
};

// Booking Status
const BOOKING_STATUS = {
  PENDING_PARTIAL_PAYMENT: 'PENDING_PARTIAL_PAYMENT',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  ASSIGNED: 'ASSIGNED',
  FULLY_PAID: 'FULLY_PAID',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

// Payment Status
const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
};

// Payment Methods
const PAYMENT_METHODS = {
  ONLINE: 'ONLINE',
  CASH: 'CASH'
};

// Package Categories
const PACKAGE_CATEGORIES = {
  WEDDING: 'WEDDING',
  BIRTHDAY: 'BIRTHDAY',
  HALDI: 'HALDI',
  CORPORATE: 'CORPORATE',
  BABY_SHOWER: 'BABY_SHOWER'
};

export {
  USER_ROLES,
  BOOKING_STATUS,
  PAYMENT_STATUS,
  PAYMENT_METHODS,
  PACKAGE_CATEGORIES
};
